### ISSUE TITLE
Able to mint duplicate Krebit - Verifiable Credentials

### ISSUE THREAD

**Issue by unijaychie** [KrebitDAO/krebit#122]
![image](https://user-images.githubusercontent.com/22148449/196016078-771eb496-b77f-47c7-a478-7676bb393c46.png)
I accidentally double minted Verified Github

wallet address 0x192513387b1BC31597EbF9f858e19bcb410EaD6B

**Comment by krebit** [comment]
Hi, it seems you created 2 separate credentials, and you minted one NFT per credential, which is the expected behaviour.
